//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHSE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuizResult
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuizResult()
        {
            this.QuestionResponses = new HashSet<QuestionResponse>();
        }
    
        public int ResultId { get; set; }
        public Nullable<int> QuizId { get; set; }
        public string Username { get; set; }
        public string Name { get; set; }
        public Nullable<int> Correct { get; set; }
        public Nullable<int> Incorrect { get; set; }
        public Nullable<System.DateTime> TimeSubmitted { get; set; }
        public string Result { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuestionResponse> QuestionResponses { get; set; }
        public virtual Quiz Quiz { get; set; }
    }
}
