//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHSE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public string ReportNo { get; set; }
        public string Location { get; set; }
        public string Classification { get; set; }
        public System.DateTime Date { get; set; }
        public string SubmitterName { get; set; }
        public string Description { get; set; }
        public string Memo { get; set; }
        public string PhotoPath { get; set; }
    }
}
