//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHSEQuiz.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionResponse
    {
        public int ResponseId { get; set; }
        public Nullable<int> ResultId { get; set; }
        public Nullable<int> QuestionId { get; set; }
        public Nullable<int> OptionId { get; set; }
        public Nullable<System.DateTime> TimeSubmitted { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual QuestionOption QuestionOption { get; set; }
        public virtual QuizResult QuizResult { get; set; }
    }
}
