//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHSEQuiz.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuizDateRange
    {
        public int QuizDateId { get; set; }
        public Nullable<int> QuizId { get; set; }
        public Nullable<int> HubId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual Hub Hub { get; set; }
        public virtual Quiz Quiz { get; set; }
    }
}
